# Rust formatting configuration
# See: https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 120
tab_spaces = 4
use_small_heuristics = "Default"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
